name: Build and publish docs

on: push

jobs:
  build_docs:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install OS dependencies
        run: |
          sudo apt update
          sudo apt install libportaudio2
      - name: Install Python dependencies
        run: |
          pip install -r docs/requirements.txt
      - name: Build docs using sphinx
        run: |
          sphinx-build docs build/html
      - name: Move docs to temporary folder
        run: |
          mv build/html /tmp/
      - name: Checkout gh-pages and copy content
        run: |
          git checkout gh-pages
          mv /tmp/html/* .
          git add .
          git commit -m "Update docs"
      - name: Push docs to github pages
        uses: ./.github/actions/remote_push
        with:
          remote_url: git@github.com:cegeme/iracema.git
          remote_branch: gh-pages
          private_ssh_key: ${{secrets.CEGEME_BOT_PRIVATE_SSH_KEY}}
