name: Tests

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install OS dependencies
      run: |
        sudo apt update
        sudo apt -y install libportaudio2
        sudo apt -y install apt-utils gcc libpq-dev libsndfile-dev

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        pip install -e .
    - name: Run tests
      run: |
        pytest --no-audio-play
